### ISSUE TITLE
 Filename too long

### ISSUE THREAD

**Issue by shmilylty** [PeiQi0/PeiQi-WIKI-Book#11]
师傅 Windows使用git克隆会遇到文件名太长的问题 这个2个图片名能改短些吗
error: unable to create file docs/.vuepress/dist/img/68747470733a2f2f7261772e6769746875622e636f6d2f4173636f7462652f496d6167652f6d61737465722f4b65726e656c6875622f4356452d323032322d32313838325f57696e646f77735f31305f323168325f5836342e676966-20220420095052148.gif: Filename too long
error: unable to create file docs/.vuepress/public/img/68747470733a2f2f7261772e6769746875622e636f6d2f4173636f7462652f496d6167652f6d61737465722f4b65726e656c6875622f4356452d323032322d32313838325f57696e646f77735f31305f323168325f5836342e676966-20220420095052148.gif: Filename too long

**Comment by PeiQi0** [comment]
可以用Docker拉镜像，然后git pull 同步会好点

**Comment by PeiQi0** [comment]
回头我改下，感谢建议
