### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by spacellx** [PeiQi0/PeiQi-WIKI-Book#20]
在执行yarn run docs:dev 出现这种错误
![QQ截图20230723143151](https://github.com/PeiQi0/PeiQi-WIKI-Book/assets/97867426/acb057b3-aaa1-43ee-b6cf-aaeb057d8c90)

**Comment by bmy12138** [comment]
export NODE_OPTIONS=--openssl-legacy-provider,输入完再跑
