### ISSUE TITLE
怎么跟在线WIKI不同步呀!整个jkens自动发布docker呀

### ISSUE THREAD

**Issue by cqkenuo** [PeiQi0/PeiQi-WIKI-Book#3]
怎么跟在线WIKI不同步呀!整个jkens自动发布docker呀

**Comment by PeiQi0** [comment]
目前Dokcer不同步更新，等文库其他模块全部完善后在准备这个功能

**Comment by PeiQi0** [comment]
Docker镜像更新了, 感谢师傅的建议
https://hub.docker.com/repository/docker/peiqipeiqi/peiqi_wiki/general

**Comment by cqkenuo** [comment]
好像依然不会自动更新

**Comment by PeiQi0** [comment]
默认一天一同步，发现Github更新，可以手动进入Docker 文库目录运行 .sh 脚本同步
