### ISSUE TITLE
请问docker版需要怎么同步

### ISSUE THREAD

**Issue by r0th-m** [PeiQi0/PeiQi-WIKI-Book#4]
请问docker版需要怎么同步

**Comment by PeiQi0** [comment]
目前Dokcer不同步更新，等文库其他模块全部完善后在准备这个功能

**Comment by linuka-deception** [comment]
![image](https://user-images.githubusercontent.com/82010937/236607608-dbbacea1-d9d0-469c-ae86-aeef3dcc2583.png)
账号密码是多少啊，docker run起来就这样
