### ISSUE TITLE
好像docker并不会同步更新gitee，建议在docker中内置一个sh脚本

### ISSUE THREAD

**Issue by cqkenuo** [PeiQi0/PeiQi-WIKI-Book#5]
好像docker并不会同步更新gitee，建议在docker中内置一个sh脚本进行每天自动定时任务自动从gitee仓库更新，然后将磁盘挂载宿主机这种方式会更好点

**Comment by PeiQi0** [comment]
Tag:0420 的 Docker已经采用此方法

<img width="780" alt="image" src="https://user-images.githubusercontent.com/63465298/163659213-a845d560-bae3-4342-8183-613502fae99d.png">

定时任务默认一天一自动更新
<img width="857" alt="image" src="https://user-images.githubusercontent.com/63465298/163659644-23a42d2c-d8b3-4fc4-8902-1c17f3eedf80.png">

**Comment by cqkenuo** [comment]
我测试了好像并不会自动更新

**Comment by cqkenuo** [comment]
需要手动执行该命令才能更新

**Comment by PeiQi0** [comment]
嗷嗷 等下我看看😊

**Comment by cqkenuo** [comment]
> 嗷嗷 等下我看看😊

大佬发个联系方式呗！一起搞搞基？

**Comment by PeiQi0** [comment]
公众号里面加我wx就好
