### ISSUE TITLE
浏览网站火绒会一直弹窗报毒

### ISSUE THREAD

**Issue by Baikeryoyo** [PeiQi0/PeiQi-WIKI-Book#6]
有点难受，它会一直弹窗
![image](https://user-images.githubusercontent.com/57838797/163783614-b2079c09-47d4-491d-ba75-2381a79be58f.png)

**Comment by PeiQi0** [comment]
JS里的，网站加白就好，不影响使用

**Comment by Gu-f** [comment]
除了会引起告警系统的告警外，不清楚作者放这几个脚本的作用是什么，分析了下，这几个脚本对文库网站好像并没有什么实际作用，作者可以声明下吗？，如果确实没有什么实际用途，是否可以考虑移除呢。

**Comment by PeiQi0** [comment]
只是单纯的Payload被渲染到JS里，被火绒误报了
