### ISSUE TITLE
wiki两个漏洞写串了

### ISSUE THREAD

**Issue by LSForever** [PeiQi0/PeiQi-WIKI-Book#9]
https://github.com/PeiQi0/PeiQi-WIKI-Book/blob/main/docs/wiki/webapp/H3C/H3C%20SecParh%E5%A0%A1%E5%9E%92%E6%9C%BA%20data_provider.php%20%E8%BF%9C%E7%A8%8B%E5%91%BD%E4%BB%A4%E6%89%A7%E8%A1%8C%E6%BC%8F%E6%B4%9E.md
和
https://github.com/PeiQi0/PeiQi-WIKI-Book/blob/main/docs/wiki/webapp/H3C/H3C%20SecParh%E5%A0%A1%E5%9E%92%E6%9C%BA%20get_detail_view.php%20%E4%BB%BB%E6%84%8F%E7%94%A8%E6%88%B7%E7%99%BB%E5%BD%95%E6%BC%8F%E6%B4%9E.md
写串了，或者可以整合成一个

**Comment by PeiQi0** [comment]
其中一个是后台权限的漏洞，需要组合使用的
